version: "3.8"

services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8976:80"
      - "8977:443"
    restart: unless-stopped
    volumes:
      - ./app/src:/var/www/html

  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: db_blog_novembre
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql


volumes:
  data:
